### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by An-undertale-fan** [sirmordred/Android-AudioVideoRecorder#1]
Wher do i downloaded???

**Comment by sirmordred** [comment]
there is no prebuilt apk for now, you can compile it from sources 👍  all you need is android studio

**Comment by An-undertale-fan** [comment]
> there is no prebuilt apk for now, you can compile it from sources 👍 all you need is android studio

On well i don't have a pc/laptop so i will try to make a workflow in github thx for the information
